// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clock.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	clock.proto

It has these top-level messages:
	GetTimeRequest
	GetTimeResponse
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetTimeRequest struct {
	Timezone string `protobuf:"bytes,1,opt,name=timezone" json:"timezone,omitempty"`
}

func (m *GetTimeRequest) Reset()                    { *m = GetTimeRequest{} }
func (m *GetTimeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTimeRequest) ProtoMessage()               {}
func (*GetTimeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetTimeRequest) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

type GetTimeResponse struct {
	FormattedTime string `protobuf:"bytes,1,opt,name=formattedTime" json:"formattedTime,omitempty"`
}

func (m *GetTimeResponse) Reset()                    { *m = GetTimeResponse{} }
func (m *GetTimeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTimeResponse) ProtoMessage()               {}
func (*GetTimeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetTimeResponse) GetFormattedTime() string {
	if m != nil {
		return m.FormattedTime
	}
	return ""
}

func init() {
	proto.RegisterType((*GetTimeRequest)(nil), "main.GetTimeRequest")
	proto.RegisterType((*GetTimeResponse)(nil), "main.GetTimeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ClockService service

type ClockServiceClient interface {
	GetTime(ctx context.Context, in *GetTimeRequest, opts ...grpc.CallOption) (*GetTimeResponse, error)
}

type clockServiceClient struct {
	cc *grpc.ClientConn
}

func NewClockServiceClient(cc *grpc.ClientConn) ClockServiceClient {
	return &clockServiceClient{cc}
}

func (c *clockServiceClient) GetTime(ctx context.Context, in *GetTimeRequest, opts ...grpc.CallOption) (*GetTimeResponse, error) {
	out := new(GetTimeResponse)
	err := grpc.Invoke(ctx, "/main.ClockService/GetTime", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ClockService service

type ClockServiceServer interface {
	GetTime(context.Context, *GetTimeRequest) (*GetTimeResponse, error)
}

func RegisterClockServiceServer(s *grpc.Server, srv ClockServiceServer) {
	s.RegisterService(&_ClockService_serviceDesc, srv)
}

func _ClockService_GetTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClockServiceServer).GetTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ClockService/GetTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClockServiceServer).GetTime(ctx, req.(*GetTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClockService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.ClockService",
	HandlerType: (*ClockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTime",
			Handler:    _ClockService_GetTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clock.proto",
}

func init() { proto.RegisterFile("clock.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xce, 0xc9, 0x4f,
	0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xd2, 0xe1,
	0xe2, 0x73, 0x4f, 0x2d, 0x09, 0xc9, 0xcc, 0x4d, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11,
	0x92, 0xe2, 0xe2, 0x28, 0xc9, 0xcc, 0x4d, 0xad, 0xca, 0xcf, 0x4b, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x82, 0xf3, 0x95, 0xcc, 0xb9, 0xf8, 0xe1, 0xaa, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53,
	0x85, 0x54, 0xb8, 0x78, 0xd3, 0xf2, 0x8b, 0x72, 0x13, 0x4b, 0x4a, 0x52, 0x53, 0x40, 0x12, 0x50,
	0x3d, 0xa8, 0x82, 0x46, 0x1e, 0x5c, 0x3c, 0xce, 0x20, 0xbb, 0x83, 0x53, 0x8b, 0xca, 0x32, 0x93,
	0x53, 0x85, 0x2c, 0xb8, 0xd8, 0xa1, 0x06, 0x09, 0x89, 0xe8, 0x81, 0x1c, 0xa2, 0x87, 0xea, 0x0a,
	0x29, 0x51, 0x34, 0x51, 0x88, 0x6d, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0xd7, 0x1b, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x70, 0xe9, 0xd7, 0x34, 0xcc, 0x00, 0x00, 0x00,
}
